### ISSUE TITLE
Null-safe version on pub.dev

### ISSUE THREAD

**Issue by marchellodev** [NikSWE/flutter_feather_icons#6]
Hey, there seem to be no v1.0.5-nullsafety.0 version on pub.dev

![image](https://user-images.githubusercontent.com/61112084/111671381-90d35780-8821-11eb-8fec-047b74bc4fbc.png)

Thanks for such an amazing package!

**Comment by inc16sec** [comment]
I'm also using flutter_feather_icons and still waiting for an update that handles null-safety. Hopefully will get to see and update soon so we can migrate the project to null-safety.

**Comment by Supercaly** [comment]
For the moment I suggest using the GitHub reference in `pubspec.yaml`

```yaml
flutter_feather_icons:
    git:
      url: https://github.com/NikSWE/flutter_feather_icons
```
